/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface": "#141313",
        "on-error": "#690005",
        "on-secondary-fixed": "#161c21",
        "outline": "#8e9192",
        "error-container": "#93000a",
        "inverse-surface": "#e5e2e1",
        "background": "#141313",
        "surface-container-highest": "#353434",
        "tertiary-fixed-dim": "#cec5c2",
        "secondary-container": "#41474d",
        "on-secondary-container": "#b0b6bc",
        "surface-container": "#201f1f",
        "on-secondary-fixed-variant": "#41474d",
        "surface-tint": "#c6c6c6",
        "secondary-fixed": "#dde3e9",
        "on-primary-container": "#636465",
        "on-tertiary-fixed": "#1f1b19",
        "on-background": "#e5e2e1",
        "outline-variant": "#444748",
        "on-error-container": "#ffdad6",
        "surface-dim": "#141313",
        "surface-bright": "#3a3939",
        "inverse-on-surface": "#313030",
        "on-tertiary-container": "#6a6361",
        "primary-fixed-dim": "#c6c6c6",
        "primary": "#ffffff",
        "surface-container-low": "#1c1b1b",
        "on-surface-variant": "#c4c7c8",
        "on-tertiary": "#342f2e",
        "on-secondary": "#2b3136",
        "primary-fixed": "#e2e2e2",
        "on-primary": "#2f3131",
        "inverse-primary": "#5d5f5f",
        "on-primary-fixed": "#1a1c1c",
        "on-tertiary-fixed-variant": "#4b4544",
        "secondary-fixed-dim": "#c1c7cd",
        "surface-container-high": "#2a2a2a",
        "surface-variant": "#353434",
        "tertiary-fixed": "#eae0dd",
        "on-surface": "#e5e2e1",
        "secondary": "#c1c7cd",
        "tertiary-container": "#eae0dd",
        "error": "#ffb4ab",
        "on-primary-fixed-variant": "#454747",
        "tertiary": "#ffffff",
        "primary-container": "#e2e2e2",
        "surface-container-lowest": "#0e0e0e",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      spacing: {
        "unit": "4px",
        "card-padding": "20px",
        "gutter": "16px",
        "stack-gap": "8px",
        "margin-page": "24px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "label-caps": ["Inter", "sans-serif"],
        "sans": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "display-lg-mobile": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "data-mono": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "label-caps": ["11px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
      },
    },
  },
  plugins: [],
};
